//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutunamayanlar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HGS_Banka
    {
        public string HGSNumarası { get; set; }
        public Nullable<decimal> hgsBakiyesi { get; set; }
        public Nullable<long> HGSMusteriNumarasi { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
