//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGS_REST_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class havale_virman
    {
        public int islemID { get; set; }
        public Nullable<System.DateTime> islemTarihi { get; set; }
        public string turu { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public string aliciHesapNo { get; set; }
        public string gondericiHesapNo { get; set; }
        public string platform { get; set; }
    
        public virtual hesap hesap { get; set; }
        public virtual hesap hesap1 { get; set; }
    }
}
