//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGS_REST_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class HGS_Kurum
    {
        public string HGSNO { get; set; }
        public Nullable<decimal> hgsBakiye { get; set; }
        public Nullable<long> musteriNumarasi { get; set; }
    }
}
