//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutunamayanlar.HGS_WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HGS_WebService.HGSSoap")]
    public interface HGSSoap {
        
        // CODEGEN: Generating message contract since element name satinAlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satinAl", ReplyAction="*")]
        Tutunamayanlar.HGS_WebService.satinAlResponse satinAl(Tutunamayanlar.HGS_WebService.satinAlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/satinAl", ReplyAction="*")]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.satinAlResponse> satinAlAsync(Tutunamayanlar.HGS_WebService.satinAlRequest request);
        
        // CODEGEN: Generating message contract since element name hgsNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bakiyeSorgula", ReplyAction="*")]
        Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse bakiyeSorgula(Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bakiyeSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse> bakiyeSorgulaAsync(Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest request);
        
        // CODEGEN: Generating message contract since element name hgsNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bakiyeYukle", ReplyAction="*")]
        Tutunamayanlar.HGS_WebService.bakiyeYukleResponse bakiyeYukle(Tutunamayanlar.HGS_WebService.bakiyeYukleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bakiyeYukle", ReplyAction="*")]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeYukleResponse> bakiyeYukleAsync(Tutunamayanlar.HGS_WebService.bakiyeYukleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgslerim", ReplyAction="*")]
        int hgslerim(long musteriNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgslerim", ReplyAction="*")]
        System.Threading.Tasks.Task<int> hgslerimAsync(long musteriNo);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class satinAlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="satinAl", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.satinAlRequestBody Body;
        
        public satinAlRequest() {
        }
        
        public satinAlRequest(Tutunamayanlar.HGS_WebService.satinAlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class satinAlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long musteriNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal bakiye;
        
        public satinAlRequestBody() {
        }
        
        public satinAlRequestBody(long musteriNo, decimal bakiye) {
            this.musteriNo = musteriNo;
            this.bakiye = bakiye;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class satinAlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="satinAlResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.satinAlResponseBody Body;
        
        public satinAlResponse() {
        }
        
        public satinAlResponse(Tutunamayanlar.HGS_WebService.satinAlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class satinAlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string satinAlResult;
        
        public satinAlResponseBody() {
        }
        
        public satinAlResponseBody(string satinAlResult) {
            this.satinAlResult = satinAlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bakiyeSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bakiyeSorgula", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequestBody Body;
        
        public bakiyeSorgulaRequest() {
        }
        
        public bakiyeSorgulaRequest(Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bakiyeSorgulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hgsNo;
        
        public bakiyeSorgulaRequestBody() {
        }
        
        public bakiyeSorgulaRequestBody(string hgsNo) {
            this.hgsNo = hgsNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bakiyeSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bakiyeSorgulaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponseBody Body;
        
        public bakiyeSorgulaResponse() {
        }
        
        public bakiyeSorgulaResponse(Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bakiyeSorgulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bakiyeSorgulaResult;
        
        public bakiyeSorgulaResponseBody() {
        }
        
        public bakiyeSorgulaResponseBody(string bakiyeSorgulaResult) {
            this.bakiyeSorgulaResult = bakiyeSorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bakiyeYukleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bakiyeYukle", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.bakiyeYukleRequestBody Body;
        
        public bakiyeYukleRequest() {
        }
        
        public bakiyeYukleRequest(Tutunamayanlar.HGS_WebService.bakiyeYukleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bakiyeYukleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hgsNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal tutar;
        
        public bakiyeYukleRequestBody() {
        }
        
        public bakiyeYukleRequestBody(string hgsNo, decimal tutar) {
            this.hgsNo = hgsNo;
            this.tutar = tutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bakiyeYukleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bakiyeYukleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tutunamayanlar.HGS_WebService.bakiyeYukleResponseBody Body;
        
        public bakiyeYukleResponse() {
        }
        
        public bakiyeYukleResponse(Tutunamayanlar.HGS_WebService.bakiyeYukleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bakiyeYukleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bakiyeYukleResult;
        
        public bakiyeYukleResponseBody() {
        }
        
        public bakiyeYukleResponseBody(string bakiyeYukleResult) {
            this.bakiyeYukleResult = bakiyeYukleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HGSSoapChannel : Tutunamayanlar.HGS_WebService.HGSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HGSSoapClient : System.ServiceModel.ClientBase<Tutunamayanlar.HGS_WebService.HGSSoap>, Tutunamayanlar.HGS_WebService.HGSSoap {
        
        public HGSSoapClient() {
        }
        
        public HGSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HGSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HGSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HGSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tutunamayanlar.HGS_WebService.satinAlResponse Tutunamayanlar.HGS_WebService.HGSSoap.satinAl(Tutunamayanlar.HGS_WebService.satinAlRequest request) {
            return base.Channel.satinAl(request);
        }
        
        public string satinAl(long musteriNo, decimal bakiye) {
            Tutunamayanlar.HGS_WebService.satinAlRequest inValue = new Tutunamayanlar.HGS_WebService.satinAlRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.satinAlRequestBody();
            inValue.Body.musteriNo = musteriNo;
            inValue.Body.bakiye = bakiye;
            Tutunamayanlar.HGS_WebService.satinAlResponse retVal = ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).satinAl(inValue);
            return retVal.Body.satinAlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.satinAlResponse> Tutunamayanlar.HGS_WebService.HGSSoap.satinAlAsync(Tutunamayanlar.HGS_WebService.satinAlRequest request) {
            return base.Channel.satinAlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.satinAlResponse> satinAlAsync(long musteriNo, decimal bakiye) {
            Tutunamayanlar.HGS_WebService.satinAlRequest inValue = new Tutunamayanlar.HGS_WebService.satinAlRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.satinAlRequestBody();
            inValue.Body.musteriNo = musteriNo;
            inValue.Body.bakiye = bakiye;
            return ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).satinAlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse Tutunamayanlar.HGS_WebService.HGSSoap.bakiyeSorgula(Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest request) {
            return base.Channel.bakiyeSorgula(request);
        }
        
        public string bakiyeSorgula(string hgsNo) {
            Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest inValue = new Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequestBody();
            inValue.Body.hgsNo = hgsNo;
            Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse retVal = ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).bakiyeSorgula(inValue);
            return retVal.Body.bakiyeSorgulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse> Tutunamayanlar.HGS_WebService.HGSSoap.bakiyeSorgulaAsync(Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest request) {
            return base.Channel.bakiyeSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeSorgulaResponse> bakiyeSorgulaAsync(string hgsNo) {
            Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest inValue = new Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.bakiyeSorgulaRequestBody();
            inValue.Body.hgsNo = hgsNo;
            return ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).bakiyeSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tutunamayanlar.HGS_WebService.bakiyeYukleResponse Tutunamayanlar.HGS_WebService.HGSSoap.bakiyeYukle(Tutunamayanlar.HGS_WebService.bakiyeYukleRequest request) {
            return base.Channel.bakiyeYukle(request);
        }
        
        public string bakiyeYukle(string hgsNo, decimal tutar) {
            Tutunamayanlar.HGS_WebService.bakiyeYukleRequest inValue = new Tutunamayanlar.HGS_WebService.bakiyeYukleRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.bakiyeYukleRequestBody();
            inValue.Body.hgsNo = hgsNo;
            inValue.Body.tutar = tutar;
            Tutunamayanlar.HGS_WebService.bakiyeYukleResponse retVal = ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).bakiyeYukle(inValue);
            return retVal.Body.bakiyeYukleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeYukleResponse> Tutunamayanlar.HGS_WebService.HGSSoap.bakiyeYukleAsync(Tutunamayanlar.HGS_WebService.bakiyeYukleRequest request) {
            return base.Channel.bakiyeYukleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tutunamayanlar.HGS_WebService.bakiyeYukleResponse> bakiyeYukleAsync(string hgsNo, decimal tutar) {
            Tutunamayanlar.HGS_WebService.bakiyeYukleRequest inValue = new Tutunamayanlar.HGS_WebService.bakiyeYukleRequest();
            inValue.Body = new Tutunamayanlar.HGS_WebService.bakiyeYukleRequestBody();
            inValue.Body.hgsNo = hgsNo;
            inValue.Body.tutar = tutar;
            return ((Tutunamayanlar.HGS_WebService.HGSSoap)(this)).bakiyeYukleAsync(inValue);
        }
        
        public int hgslerim(long musteriNo) {
            return base.Channel.hgslerim(musteriNo);
        }
        
        public System.Threading.Tasks.Task<int> hgslerimAsync(long musteriNo) {
            return base.Channel.hgslerimAsync(musteriNo);
        }
    }
}
