//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class havale_virman
{
    public int islemID { get; set; }
    public Nullable<System.DateTime> islemTarihi { get; set; }
    public string turu { get; set; }
    public Nullable<decimal> tutar { get; set; }
    public string aliciHesapNo { get; set; }
    public string gondericiHesapNo { get; set; }
    public string platform { get; set; }

    public virtual hesap hesap { get; set; }
    public virtual hesap hesap1 { get; set; }
}

public partial class hesap
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public hesap()
    {
        this.havale_virman = new HashSet<havale_virman>();
        this.havale_virman1 = new HashSet<havale_virman>();
    }

    public string hesapNo { get; set; }
    public Nullable<long> musteriNo { get; set; }
    public Nullable<decimal> bakiye { get; set; }
    public Nullable<bool> aktiflikDurumu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<havale_virman> havale_virman { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<havale_virman> havale_virman1 { get; set; }
    public virtual kullanici kullanici { get; set; }
}

public partial class HGS_Banka
{
    public string HGSNumarası { get; set; }
    public Nullable<decimal> hgsBakiyesi { get; set; }
    public Nullable<long> HGSMusteriNumarasi { get; set; }

    public virtual kullanici kullanici { get; set; }
}

public partial class HGS_Kurum
{
    public string HGSNO { get; set; }
    public Nullable<decimal> hgsBakiye { get; set; }
    public Nullable<long> musteriNumarasi { get; set; }
}

public partial class kullanici
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public kullanici()
    {
        this.hesap = new HashSet<hesap>();
        this.HGS_Banka = new HashSet<HGS_Banka>();
    }

    public long musteriNo { get; set; }
    public string ad { get; set; }
    public string soyad { get; set; }
    public string TCKN { get; set; }
    public string sifre { get; set; }
    public string email { get; set; }
    public string adres { get; set; }
    public string telefon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<hesap> hesap { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HGS_Banka> HGS_Banka { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
